In [1]:
import pandas as pd
import numpy as np
from montecarlo.montecarlo import Die, Game, Analyzer

sides = np.array([1,2,3,5])
d = Die(sides)

/home/hrn4ch/.local/lib/python3.8/site-packages/pandas/core/computation/expressions.py:20: UserWarning: Pandas requires version '2.7.3' or newer of 'numexpr' (version '2.7.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED


In [2]:
type(sides)

numpy.ndarray

In [3]:
isinstance(sides, np.ndarray)

True

In [4]:
df = pd.DataFrame({'sides':sides, 'weights':[1]*len(sides)})
df = df.set_index('sides')

In [5]:
df.sample(3, replace=True, weights=df['weights']).index.to_list()

[2, 2, 2]

In [6]:
df['weights'][5]

1

In [7]:
d.change_weight(5, 4)
d.state()

weights
sides         
1            1
2            1
3            1
5            4

In [8]:
x = np.array(d.roll(100))
np.unique(x, return_counts=True)

(array([1, 2, 3, 5]), array([15, 12, 13, 60]))

In [9]:
df.sample(5, replace=True, weights=df['weights'])

weights
sides         
3            1
2            1
2            1
2            1
3            1

In [10]:
x = pd.DataFrame()


In [11]:
d1 = Die(np.array([1,2,3]))
d2 = Die(np.array([1,2,3]))
d3 = Die(np.array([1,2,3]))

dice = [d1,d2,d3]
g = Game(dice)

In [12]:
g.play(4)
y = g.last_play()
y

dice-0  dice-1  dice-2
roll                        
0          2       3       3
1          1       2       3
2          2       2       2
3          1       3       2

In [13]:
x =g.last_play(True)
x.value_counts()

outcome
2          6
3          4
1          2
Name: count, dtype: int64

In [14]:
isinstance(g, Game)

True

In [15]:
type(y.index)

pandas.core.indexes.base.Index

In [17]:
df = g.last_play()

In [18]:
d1.change_weight(1, 1)
d2.change_weight(1, 1)
d3.change_weight(1, 1)

In [19]:
g.play(8)
df = g.last_play()
df

dice-0  dice-1  dice-2
roll                        
0          2       1       1
1          1       3       2
2          3       3       2
3          2       3       1
4          2       3       1
5          2       1       2
6          2       2       3
7          2       2       2

In [20]:
len(df['dice-0'].unique())

3

In [21]:
def jackpot(df):
    count = 0
    for c in df.columns:
        if len(df[c].unique())==1:
            count+=1
    return count
jackpot(df)

0

In [22]:
count = 0
for i in df.index:
    print(df.iloc[i].unique())
    if len(df.iloc[i].unique())==1:
        count+=1
count

[2 1]
[1 3 2]
[3 2]
[2 3 1]
[2 3 1]
[2 1]
[2 3]
[2]


1

In [23]:
wombocombos = pd.DataFrame(df.value_counts())
wombocombos.reset_index()

dice-0  dice-1  dice-2  count
0       2       3       1      2
1       1       3       2      1
2       2       1       1      1
3       2       1       2      1
4       2       2       2      1
5       2       2       3      1
6       3       3       2      1

In [24]:
df

dice-0  dice-1  dice-2
roll                        
0          2       1       1
1          1       3       2
2          3       3       2
3          2       3       1
4          2       3       1
5          2       1       2
6          2       2       3
7          2       2       2

In [25]:
pd.DataFrame(np.sort(df.values, axis=1)).groupby([0,1,2]).value_counts()

0  1  2
1  1  2    1
   2  2    1
      3    3
2  2  2    1
      3    1
   3  3    1
Name: count, dtype: int64

In [26]:
combo = pd.DataFrame(np.sort(df.values, axis=1)).groupby([i for i in range(len(df.columns))]).value_counts()
combodf = pd.DataFrame(combo)
combodf

count
0 1 2       
1 1 2      1
  2 2      1
    3      3
2 2 2      1
    3      1
  3 3      1

In [2]:
d11 = Die(np.array([1,2,3]))
d21 = Die(np.array([1,2,3]))
d31 = Die(np.array([1,2,3]))

dice1 = [d11,d21,d31]
g1 = Game(dice1)

In [3]:
g1.play(9)
g1.last_play(False)

dice-0  dice-1  dice-2
roll                        
0          3       1       3
1          3       3       2
2          3       1       2
3          1       1       3
4          3       3       1
5          2       1       3
6          1       1       2
7          1       1       1
8          3       1       2

In [4]:
a = Analyzer(g1)
a.permutations()

count
dice-0 dice-1 dice-2       
3      1      2           2
1      1      1           1
              2           1
              3           1
2      1      3           1
3      1      3           1
       3      1           1
              2           1

In [5]:
a.combos()

count
0 1 2       
1 1 1      1
    2      1
    3      1
  2 3      3
  3 3      2
2 3 3      1

In [34]:
df = g1.last_play(False)
np.unique(df.values)

array([1, 2, 3])

In [28]:
unique, counts = np.unique(df.iloc[0], return_counts=True)

In [32]:
d.sides

dice-0  dice-1  dice-2
roll                        
0          3       1       3
1          3       3       2
2          3       1       2
3          1       1       3
4          3       3       1
5          2       1       3
6          1       1       2
7          1       1       1
8          3       1       2

In [29]:
unique

array([1, 3])

In [30]:
counts

array([1, 2])

In [31]:
c = {k:[] for k in df.index}
face = pd.DataFrame({})
d[unique] = counts

TypeError: 'type' object does not support item assignment

In [47]:
d11.change_weight(1, 784)
d11.state()

weights
sides         
1          784
2            1
3            1

In [57]:
d11.state().loc[1].item()

784

In [60]:
!python montecarlo/montecarlo_test.py

/home/hrn4ch/.local/lib/python3.8/site-packages/pandas/core/computation/expressions.py:20: UserWarning: Pandas requires version '2.7.3' or newer of 'numexpr' (version '2.7.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
test_analyzer_combos (__main__.MontecarloTestSuite) ... ok
test_analyzer_face_counts (__main__.MontecarloTestSuite) ... ok
test_analyzer_jackpot (__main__.MontecarloTestSuite) ... ok
test_analyzer_permutations (__main__.MontecarloTestSuite) ... ok
test_die_change_weight (__main__.MontecarloTestSuite) ... ok
test_die_roll (__main__.MontecarloTestSuite) ... ok
test_die_state (__main__.MontecarloTestSuite) ... ok
test_game_last_play (__main__.MontecarloTestSuite) ... ok
test_game_play (__main__.MontecarloTestSuite) ... ok

----------------------------------------------------------------------
Ran 9 tests in 0.027s

OK
